apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eszett-log.fullname" . }}
  labels:
    {{- include "eszett-log.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
