apiVersion: v1
kind: Service
metadata:
  name: {{ include "eszett-log.fullname" . }}
  labels:
    {{- include "eszett-log.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "eszett-log.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3001
      protocol: TCP
