apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eszett-log-posts
  namespace: eszett-log
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eszett-log-data
  namespace: eszett-log
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eszett-log-uploads
  namespace: eszett-log
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
